logsBucket: 'gs://bucket67ut'

steps:
  # Step 1: Build and push database image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/sukrit-singh-426716/my-repo/image:v1', './tasktfcloudbuild']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/sukrit-singh-426716/my-repo/image:v1']

  #Step2:
  - name: 'hashicorp/terraform:1.0.0'
    args: ['init']
  - name: 'hashicorp/terraform:1.0.0'
    args: ['apply', '-auto-approve']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'       
